sudo: false

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CC=true
    - php: 7
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - if [[ $EXECUTE_CS_CC == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CC == 'true' ]]; then composer require squizlabs/php_codesniffer && ./vendor/bin/phpcs ; fi

after_script:
  - if [[ $EXECUTE_CS_CC == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
