sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CC=true
    - php: 7
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - if [[ $EXECUTE_CS_CC == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CC == 'true' ]]; then composer require squizlabs/php_codesniffer && ./vendor/bin/phpcs ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
