sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer require squizlabs/php_codesniffer && ./vendor/bin/phpcs ; fi
